### ISSUE TITLE
Unable to redirect through ingress if base_url is changed

### ISSUE THREAD

**Issue by tpettit** [srinisbook/Prometheus-grafana#1]
I am using ingress in our kubernetes cluster hosted on AWS to reduce the number of ELBs required for our cluster. When I follow the steps in the readme and apply the .yaml files everything works great! I redirected the traffic through ingress instead of using an ELB and that works great too, but if I change the base_url in the grafana config so that the invitation e-mails and links in the alert emails are pointing to our public facing DNS (we're using cloudflare) I get redirect errors in firefox and cannot load grafana. Currently all the e-mails and alerts point to localhost and obviously that won't work. Any idea how I can change those links to be the public facing DNS?

**Comment by srinisbook** [comment]
Can you please provide your Grafana configuration?

**Comment by tpettit** [comment]
@srinisbook thanks so much for the response. I actually figured it out. I had a problem with my ingress configuration.
